#    potform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target ‘CloudClass’ do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'

    pod 'GRKPageViewController', '1.2'
    pod 'Base64nl', '~> 1.2'
    pod 'Reachability', '~> 3.2'
    pod 'Realm', '0.98.3'
    pod 'OpenUDID', '~> 1.0.0'
    pod 'Shimmer', '~>1.0.2'
    pod 'SZTextView', '1.2.1'
    pod 'SwipeView', '~> 1.3.2', :inhibit_warnings => true
    pod 'Mantle', '1.5.1'
    pod 'AFNetworking', '~> 2.0'
    pod 'FMDB', '~> 2.5'
    pod 'SDWebImage', '~> 3.7.2'
    #    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Masonry', '~> 0.6.4'
    pod 'MJRefresh', '1.4.6', :inhibit_warnings => true
    pod 'XHRefreshControl', '4.1'
    pod 'FZiOSCache', :git =>'git@115.236.179.166:FZiOSCache.git',:branch => 'master'
    pod 'FWGIFImageView', :git =>'git@115.236.179.166:FWGIFImageView.git', :tag => '0.0.9'
    pod 'FZCommonCategory', :git =>'git@115.236.179.166:FZCommonCategory.git', :branch => 'master'
    pod 'FZLoginManagerSDK', :git =>'git@115.236.179.166:FZLoginManagerSDK.git',:branch => 'FunClass_1.1'
    pod 'FZNetwork', :git =>'git@115.236.179.166:FZNetwork.git',:branch => 'FunClass_1.1'
    pod 'FZLocalization', :git =>'git@115.236.179.166:FZLocalization.git',:branch => 'EnglishTalk_develop'
    pod 'FZCommonUIControl', :git =>'git@115.236.179.166:FZCommonUIControl.git', :branch => 'master'
    #pod 'UMAnalytics', :git =>'gogs@git.qupeiyin.net:yinbo.ji-ios/UMAnalytics.git',:branch => 'master'
    pod 'HMSegmentedControl', :git =>'git@115.236.179.166:HMSegmentedControl.git',:branch => 'master'
    #    pod 'FZThirdPartyLoginAndShareSDK', :git =>'git@115.236.179.166:FZThirdPartyLoginAndShareSDK.git',:branch => 'iOS9_adapt'
    #    pod 'FCChatUI', :git =>'git@115.236.179.166:FCChatUI.git',:branch => 'KidDubbing_develop_1.1'
    #    pod 'FCChatCache', :git =>'git@115.236.179.166:FCChatCache.git',:branch => 'KidDubbing_develop'
    #    pod 'FZPhotoViewer', :git =>'git@115.236.179.166:FZPhotoViewer.git',:branch => 'master'
    pod 'AlipaySDK', :git =>'git@115.236.179.166:AlipaySDK.git',:branch => 'master'
##################### guangfu yang begin #########################################
#pod 'FZNetwork', :path =>'/Users/feizhu/Documents/趣课堂重构库/FZNetwork'
#pod 'FZLoginManagerSDK', :path =>'/Users/feizhu/Documents/趣课堂重构库/FZLoginManagerSDK'

#################### guangfu yang end ############################################

##################### minrui begin #########################################
#  pod 'FZNetwork', :path =>'/Users/misaka/Desktop/英语趣课堂/趣课堂重构库/FZNetwork'
#  pod 'FZLoginManagerSDK', :path =>'/Users/misaka/Desktop/英语趣课堂/趣课堂重构库/FZLoginManagerSDK',:branch => 'FunClass_1.1'

#################### minrui end ############################################


end
